#use the latest version of nodeJS
FROM node:18-alpine

#set the working directory inside the folder
WORKDIR /app

#copy package and package-loc.json
COPY package*.json ./

#install dependicies
RUN npm install

#copy the rest of the application files
COPY . . 

#expose the port the app run on
EXPOSE 5173

#define command to run the app
CMD ['npm', 'start']
